apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: test2
  labels:
    app: my-app
spec:
  containers:
    - name: my-app-container
      image: nginx:latest
      env:
        - name: MY_ENV_VAR
          value: "Hello from ArgoCD"
